LAMMPS_VERSION="20220623_update4"
LAMMPS_DOWNLOAD_VERSION="stable_23Jun2022_update4"
LAMMPS_MA_REVISION=1

export __NAME__=lammps
export __VERSION__=${LAMMPS_VERSION}
export __MA_REVISION__=${LAMMPS_MA_REVISION}
