LAMMPS_VERSION="20240829_update1"
LAMMPS_DOWNLOAD_VERSION="stable_29Aug2024_update1"
LAMMPS_MA_REVISION=1

export __NAME__=lammps
export __VERSION__=${LAMMPS_VERSION}
export __MA_REVISION__=${LAMMPS_MA_REVISION}
