#!/bin/sh

TOOL="lapack fftw tcltk qt4 hdf5 python ipython boost cmake git"
APPS="alps xtapp openmx modylas feram gromacs ermod tapioca xcrysden iginition"

if [ -n "$MA_ROOT_TOOL" ]; then
  echo "MA_ROOT_TOOL: $MA_ROOT_TOOL"
  echo "MA_ROOT_APPS: $MA_ROOT_APPS"
  awk '$1=="#" && $2=="env" {print}' "$MA_ROOT_TOOL/env.sh"
  for t in $TOOL; do
    if [ -f "$MA_ROOT_APPS/$t/${t}vars.sh" ]; then
      awk '$1=="#" && $2==t {print}' t="$t" "$MA_ROOT_TOOL/$t/${t}vars.sh"
    fi
  done
  for p in $APPS; do
    if [ -f "$MA_ROOT_APPS/$p/${p}vars.sh" ]; then
      awk '$1=="#" && $2==p {print}' p="$p" "$MA_ROOT_APPS/$p/${p}vars.sh"
    fi
  done
else
  echo "MateriApps Installation not found."
  exit 127
fi
