#!/bin/sh

TOOL="gcc lapack fftw tcltk qt4 gsl hdf5 komega wxWidgets python wxPython boost cmake git"
APPS="alps xtapp openmx modylas feram gromacs lammps ermod dsqss hphi mvmc tapioca xcrysden iginition"

if [ -n "$MA_ROOT_TOOL" ]; then
  echo "MA_ROOT_TOOL: $MA_ROOT_TOOL"
  echo "MA_ROOT_APPS: $MA_ROOT_APPS"
  awk '$1=="#" && $2=="env" {print}' "$MA_ROOT_TOOL/env.sh"
  for t in $TOOL; do
    if [ -f "$MA_ROOT_TOOL/env.d/${t}vars.sh" ]; then
      awk '$1=="#" && $2==t {print}' t="$t" "$MA_ROOT_TOOL/env.d/${t}vars.sh"
    fi
  done
  for p in $APPS; do
    if [ -f "$MA_ROOT_APPS/$p/${p}vars.sh" ]; then
      awk '$1=="#" && $2==p {print}' p="$p" "$MA_ROOT_APPS/$p/${p}vars.sh"
    fi
  done
else
  echo "MateriApps Installation not found."
  exit 127
fi
