#!/bin/sh

SCRIPT_DIR=$(cd "$(dirname $0)"; pwd)
. $SCRIPT_DIR/../util.sh
. $SCRIPT_DIR/version.sh
. $SCRIPT_DIR/../03_boost/version.sh
set_prefix
set_build_dir

. $PREFIX_OPT/env.sh

mkdir -p $PREFIX_ALPS/source $PREFIX_ALPS/script
check cp -p $0 $PREFIX_ALPS/script/compile-$ALPS_VERSION.sh
check cp -p $HOME/source/alps-$ALPS_VERSION.tar.gz $PREFIX_ALPS/source/

YMDT=`date +%Y%m%d%H%M%S`
LOG=$PREFIX_ALPS/script/compile-$ALPS_VERSION.$YMDT.log
rm -f $LOG
echo "LOG=$LOG"

echo "PREFIX=$PREFIX_ALPS" > $LOG
echo "ALPS_VERSION=$ALPS_VERSION" >> $LOG
echo "BOOST_VERSION=$BOOST_VERSION" >> $LOG
echo "SCRIPT=$PREFIX_ALPS/script/compile-$ALPS_VERSION.sh" >> $LOG
echo "LOG=$LOG" >> $LOG

(cd $BUILD_DIR && tar zxf $PREFIX_ALPS/source/alps-$ALPS_VERSION.tar.gz)

### OpenMP version

VERSION=$ALPS_VERSION
echo "[start alps-$VERSION]" >> $LOG 2>&1

rm -rf $BUILD_DIR/alps-build-$VERSION.$YMDT && mkdir -p $BUILD_DIR/alps-build-$VERSION.$YMDT
cd $BUILD_DIR/alps-build-$VERSION.$YMDT
echo "[cmake]" >> $LOG 2>&1
check cmake -DCMAKE_INSTALL_PREFIX=$PREFIX_ALPS/alps-$VERSION \
  -DCMAKE_C_COMPILER="gcc-mp-4.7" -DCMAKE_CXX_COMPILER="g++-mp-4.7" -DCMAKE_Fortran_COMPILER="gfortran-mp-4.7" \
  -DPYTHON_INTERPRETER=python2.7 \
  -DBoost_ROOT_DIR=$PREFIX_OPT/boost_$BOOST_VERSION -DALPS_ENABLE_OPENMP=ON -DALPS_ENABLE_OPENMP_WORKER=ON -DALPS_BUILD_FORTRAN=ON \
  $BUILD_DIR/alps-$ALPS_VERSION >> $LOG 2>&1

echo "[make install]" >> $LOG 2>&1
check make -j2 install >> $LOG 2>&1
echo "[ctest]" >> $LOG 2>&1
ctest >> $LOG 2>&1

cp -fp $PREFIX_ALPS/alps-$VERSION/bin/alpsvars.sh $PREFIX_ALPS/alpsvars-$VERSION.sh
rm -f $PREFIX_ALPS/alpsvars.sh
ln -s alpsvars-$VERSION.sh $PREFIX_ALPS/alpsvars.sh

### no-OpenMP version

VERSION="noomp-$ALPS_VERSION"
echo "[start alps-$VERSION]" >> $LOG 2>&1

rm -rf $BUILD_DIR/alps-build-$VERSION.$YMDT && mkdir -p $BUILD_DIR/alps-build-$VERSION.$YMDT
cd $BUILD_DIR/alps-build-$VERSION.$YMDT
echo "[cmake]" >> $LOG 2>&1
check cmake -DCMAKE_INSTALL_PREFIX=$PREFIX_ALPS/alps-$VERSION \
  -DCMAKE_C_COMPILER="gcc-mp-4.7" -DCMAKE_CXX_COMPILER="g++-mp-4.7" -DCMAKE_Fortran_COMPILER="gfortran-mp-4.7" \
  -DPYTHON_INTERPRETER=python2.7 \
  -DBoost_ROOT_DIR=$PREFIX_OPT/boost_$BOOST_VERSION -DALPS_BUILD_FORTRAN=ON \
  $BUILD_DIR/alps-$ALPS_VERSION >> $LOG 2>&1

echo "[make install]" >> $LOG 2>&1
check make -j2 install >> $LOG 2>&1
echo "[ctest]" >> $LOG 2>&1
ctest >> $LOG 2>&1

cp -fp $PREFIX_ALPS/alps-$VERSION/bin/alpsvars.sh $PREFIX_ALPS/alpsvars-$VERSION.sh
rm -f $PREFIX_ALPS/alpsvars-noomp.sh
ln -s alpsvars-$VERSION.sh $PREFIX_ALPS/alpsvars-noomp.sh
