#!/bin/sh

MA_HAVE_JULIA=no
MA_JULIA=$(which julia)
MA_JULIA_VERSION=
MA_JULIA_VERSION_MAJOR=
MA_JULIA_VERSION_MINOR=
MA_JULIA_VERSION_PATCH=

if [ -n "${MA_JULIA}" ]; then
  MA_JULIA_VERSION=$(${MA_JULIA} --version | head -1 | awk '{print $3}')
  MA_JULIA_VERSION_MAJOR=$(echo ${MA_JULIA_VERSION} | cut -d . -f 1)
  MA_JULIA_VERSION_MINOR=$(echo ${MA_JULIA_VERSION} | cut -d . -f 2)
  MA_JULIA_VERSION_PATCH=$(echo ${MA_JULIA_VERSION} | cut -d . -f 3)
fi

if [ -n "${MA_JULIA_VERSION}" ]; then
  MA_HAVE_JULIA=yes
fi

<< "#__COMMENT__"
  echo "MA_HAVE_JULIA=${MA_HAVE_JULIA}"
  echo "MA_JULIA=${MA_JULIA}"
  echo "MA_JULIA_VERSION=${MA_JULIA_VERSION}"
  echo "MA_JULIA_VERSION_MAJOR=${MA_JULIA_VERSION_MAJOR}"
  echo "MA_JULIA_VERSION_MINOR=${MA_JULIA_VERSION_MINOR}"
  echo "MA_JULIA_VERSION_PATCH=${MA_JULIA_VERSION_PATCH}"
#__COMMENT__
