#!/bin/sh

MA_CMAKE=$(which cmake)
MA_CMAKE_VERSION=
MA_CMAKE_VERSION_MAJOR=
MA_CMAKE_VERSION_MINOR=
MA_CMAKE_VERSION_PATCH=

if [ -n "${MA_CMAKE}" ]; then
  MA_HAVE_CMAKE=yes
  MA_CMAKE_VERSION=$(${MA_CMAKE} --version | head -1 | awk '{print $3}')
  MA_CMAKE_VERSION_MAJOR=$(echo ${MA_CMAKE_VERSION} | cut -d . -f 1)
  MA_CMAKE_VERSION_MINOR=$(echo ${MA_CMAKE_VERSION} | cut -d . -f 2)
  MA_CMAKE_VERSION_PATCH=$(echo ${MA_CMAKE_VERSION} | cut -d . -f 3)
fi

<< "#__COMMENT__"
  echo "MA_CMAKE=${MA_CMAKE}"
  echo "MA_CMAKE_VERSION=${MA_CMAKE_VERSION}"
  echo "MA_CMAKE_VERSION_MAJOR=${MA_CMAKE_VERSION_MAJOR}"
  echo "MA_CMAKE_VERSION_MINOR=${MA_CMAKE_VERSION_MINOR}"
  echo "MA_CMAKE_VERSION_PATCH=${MA_CMAKE_VERSION_PATCH}"
#__COMMENT__
