LAPACK_VERSION="3.9.0"
OPENBLAS_VERSION="0.3.12"
LAPACK_MA_REVISION="1"

__NAME__=lapack
__NAME_BLAS__=openblas
__VERSION__=${LAPACK_VERSION}
__VERSION_BLAS__=${OPENBLAS_VERSION}
__MA_REVISION__=${LAPACK_MA_REVISION}
