set -u

rm -rf build
mkdir build
cd build

${CMAKE} \
  -DCMAKE_INSTALL_PREFIX=${PREFIX} \
  -DCMAKE_VERBOSE_MAKEFILE=1 \
  -DSPGLIB_ROOT=${SPGLIB_ROOT} \
  -DFFTW3_ROOT=${FFTW3_ROOT} \
  -DCMAKE_CXX_FLAGS="-O3 ${MA_EXTRA_FLAGS}" \
  ../
