set -u

${CMAKE} \
  -DCMAKE_INSTALL_PREFIX=${PREFIX} \
  -DCMAKE_VERBOSE_MAKEFILE=1 \
  -DCMAKE_C_FLAGS="${MA_EXTRA_FLAGS}" \
  -DCMAKE_Fortran_FLAGS="${MA_EXTRA_FLAGS}" \
  -DUSE_SCALAPACK=ON \
  -DSCALAPACK_LIBRARIES="-mkl=cluster" \
  -DCONFIG=intel \
  ../ 2>&1 | tee -a $LOG
