name: upload docs to gh-pages

on:
  push:
    branches:
      - master
      - '!gh-pages'
      - '*-autodoc'
    # tags: ['*']

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v4.x

    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: main

    - name: Checkout gh-pages
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: gh-pages

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    # - name: Prepare LaTeX env
    #   run: |
    #     sudo apt update
    #     sudo apt install \
    #       texlive-latex-recommended texlive-latex-extra texlive-xetex \
    #       texlive-lang-japanese texlive-fonts-recommended texlive-fonts-extra latexmk
    #     kanji-config-updmap-sys ipaex

    - name: Install python packages
      run: |
        python -m pip install --upgrade pip
        pip install sphinx

    - name: Build
      run: |
        for lang in ja en; do
          cd ${GITHUB_WORKSPACE}/main/docs/sphinx/${lang}
          make html
          # make latexpdf
        done

    - name: Deploy Configuration
      run: |
          mkdir ~/.ssh
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          echo "${{ secrets.GH_ACTIONS_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa

    - name: Push
      env:
        GIT_USER: "MAInstaller Developers"
        GIT_EMAIL: "mainstaller-dev@issp.u-tokyo.ac.jp"
        TARGET_NAME: ${{ env.GITHUB_REF_SLUG }}
      run: |
          cd ${GITHUB_WORKSPACE}
          is_tag=NO
          TARGET_NAME="${TARGET_NAME%-autodoc}"
          test "_$(echo ${GITHUB_REF:-'//'} | cut -d/ -f2)" = "_tags" && is_tag=YES
          for lang in ja en; do
            rm -rf "gh-pages/manual/${TARGET_NAME}/${lang}"
            mkdir -p "gh-pages/manual/${TARGET_NAME}"
            cp -r "main/docs/sphinx/${lang}/build/html" "gh-pages/manual/${TARGET_NAME}/${lang}"
            if [ $is_tag = "YES" ]; then
              :
            fi
          done
          cd gh-pages
          git config --local user.name "${GIT_USER}"
          git config --local user.email "${GIT_EMAIL}"
          git remote set-url origin git@github.com:${GITHUB_REPOSITORY}.git
          git add manual
          if git commit -m "Deploy docs to ${TARGET_NAME} by GitHub Actions triggered by ${GITHUB_SHA}"
          then
            git push origin gh-pages
          else
            echo "Nothing to deploy"
          fi
